/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as SplatRouteImport } from './routes/$'
import { Route as IndexRouteImport } from './routes/index'
import { Route as OrganizationIndexRouteImport } from './routes/organization/index'
import { Route as ExampleIndexRouteImport } from './routes/example/index'
import { Route as AccountIndexRouteImport } from './routes/account/index'
import { Route as OrganizationOrganizationViewRouteImport } from './routes/organization/$organizationView'
import { Route as ExampleFeatureIdRouteImport } from './routes/example/$featureId'
import { Route as AuthAuthViewRouteImport } from './routes/auth/$authView'
import { Route as ApiSplatRouteImport } from './routes/api/$'
import { Route as AdminQuizEditorRouteImport } from './routes/admin/quiz-editor'
import { Route as AccountAccountViewRouteImport } from './routes/account/$accountView'
import { Route as AdminResponsesResponseId_newRouteImport } from './routes/admin/responses/$responseId_new'
import { Route as AdminResponsesResponseIdRouteImport } from './routes/admin/responses/$responseId'
import { Route as AdminResponsesResponseIdAnalysisRouteImport } from './routes/admin/responses/$responseId/analysis'

const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const SplatRoute = SplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const OrganizationIndexRoute = OrganizationIndexRouteImport.update({
  id: '/organization/',
  path: '/organization/',
  getParentRoute: () => rootRouteImport,
} as any)
const ExampleIndexRoute = ExampleIndexRouteImport.update({
  id: '/example/',
  path: '/example/',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountIndexRoute = AccountIndexRouteImport.update({
  id: '/account/',
  path: '/account/',
  getParentRoute: () => rootRouteImport,
} as any)
const OrganizationOrganizationViewRoute =
  OrganizationOrganizationViewRouteImport.update({
    id: '/organization/$organizationView',
    path: '/organization/$organizationView',
    getParentRoute: () => rootRouteImport,
  } as any)
const ExampleFeatureIdRoute = ExampleFeatureIdRouteImport.update({
  id: '/example/$featureId',
  path: '/example/$featureId',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthAuthViewRoute = AuthAuthViewRouteImport.update({
  id: '/auth/$authView',
  path: '/auth/$authView',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSplatRoute = ApiSplatRouteImport.update({
  id: '/api/$',
  path: '/api/$',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminQuizEditorRoute = AdminQuizEditorRouteImport.update({
  id: '/quiz-editor',
  path: '/quiz-editor',
  getParentRoute: () => AdminRoute,
} as any)
const AccountAccountViewRoute = AccountAccountViewRouteImport.update({
  id: '/account/$accountView',
  path: '/account/$accountView',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminResponsesResponseId_newRoute =
  AdminResponsesResponseId_newRouteImport.update({
    id: '/responses/$responseId_new',
    path: '/responses/$responseId_new',
    getParentRoute: () => AdminRoute,
  } as any)
const AdminResponsesResponseIdRoute =
  AdminResponsesResponseIdRouteImport.update({
    id: '/responses/$responseId',
    path: '/responses/$responseId',
    getParentRoute: () => AdminRoute,
  } as any)
const AdminResponsesResponseIdAnalysisRoute =
  AdminResponsesResponseIdAnalysisRouteImport.update({
    id: '/analysis',
    path: '/analysis',
    getParentRoute: () => AdminResponsesResponseIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/admin': typeof AdminRouteWithChildren
  '/account/$accountView': typeof AccountAccountViewRoute
  '/admin/quiz-editor': typeof AdminQuizEditorRoute
  '/api/$': typeof ApiSplatRoute
  '/auth/$authView': typeof AuthAuthViewRoute
  '/example/$featureId': typeof ExampleFeatureIdRoute
  '/organization/$organizationView': typeof OrganizationOrganizationViewRoute
  '/account': typeof AccountIndexRoute
  '/example': typeof ExampleIndexRoute
  '/organization': typeof OrganizationIndexRoute
  '/admin/responses/$responseId': typeof AdminResponsesResponseIdRouteWithChildren
  '/admin/responses/$responseId_new': typeof AdminResponsesResponseId_newRoute
  '/admin/responses/$responseId/analysis': typeof AdminResponsesResponseIdAnalysisRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/admin': typeof AdminRouteWithChildren
  '/account/$accountView': typeof AccountAccountViewRoute
  '/admin/quiz-editor': typeof AdminQuizEditorRoute
  '/api/$': typeof ApiSplatRoute
  '/auth/$authView': typeof AuthAuthViewRoute
  '/example/$featureId': typeof ExampleFeatureIdRoute
  '/organization/$organizationView': typeof OrganizationOrganizationViewRoute
  '/account': typeof AccountIndexRoute
  '/example': typeof ExampleIndexRoute
  '/organization': typeof OrganizationIndexRoute
  '/admin/responses/$responseId': typeof AdminResponsesResponseIdRouteWithChildren
  '/admin/responses/$responseId_new': typeof AdminResponsesResponseId_newRoute
  '/admin/responses/$responseId/analysis': typeof AdminResponsesResponseIdAnalysisRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/admin': typeof AdminRouteWithChildren
  '/account/$accountView': typeof AccountAccountViewRoute
  '/admin/quiz-editor': typeof AdminQuizEditorRoute
  '/api/$': typeof ApiSplatRoute
  '/auth/$authView': typeof AuthAuthViewRoute
  '/example/$featureId': typeof ExampleFeatureIdRoute
  '/organization/$organizationView': typeof OrganizationOrganizationViewRoute
  '/account/': typeof AccountIndexRoute
  '/example/': typeof ExampleIndexRoute
  '/organization/': typeof OrganizationIndexRoute
  '/admin/responses/$responseId': typeof AdminResponsesResponseIdRouteWithChildren
  '/admin/responses/$responseId_new': typeof AdminResponsesResponseId_newRoute
  '/admin/responses/$responseId/analysis': typeof AdminResponsesResponseIdAnalysisRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$'
    | '/admin'
    | '/account/$accountView'
    | '/admin/quiz-editor'
    | '/api/$'
    | '/auth/$authView'
    | '/example/$featureId'
    | '/organization/$organizationView'
    | '/account'
    | '/example'
    | '/organization'
    | '/admin/responses/$responseId'
    | '/admin/responses/$responseId_new'
    | '/admin/responses/$responseId/analysis'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$'
    | '/admin'
    | '/account/$accountView'
    | '/admin/quiz-editor'
    | '/api/$'
    | '/auth/$authView'
    | '/example/$featureId'
    | '/organization/$organizationView'
    | '/account'
    | '/example'
    | '/organization'
    | '/admin/responses/$responseId'
    | '/admin/responses/$responseId_new'
    | '/admin/responses/$responseId/analysis'
  id:
    | '__root__'
    | '/'
    | '/$'
    | '/admin'
    | '/account/$accountView'
    | '/admin/quiz-editor'
    | '/api/$'
    | '/auth/$authView'
    | '/example/$featureId'
    | '/organization/$organizationView'
    | '/account/'
    | '/example/'
    | '/organization/'
    | '/admin/responses/$responseId'
    | '/admin/responses/$responseId_new'
    | '/admin/responses/$responseId/analysis'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SplatRoute: typeof SplatRoute
  AdminRoute: typeof AdminRouteWithChildren
  AccountAccountViewRoute: typeof AccountAccountViewRoute
  ApiSplatRoute: typeof ApiSplatRoute
  AuthAuthViewRoute: typeof AuthAuthViewRoute
  ExampleFeatureIdRoute: typeof ExampleFeatureIdRoute
  OrganizationOrganizationViewRoute: typeof OrganizationOrganizationViewRoute
  AccountIndexRoute: typeof AccountIndexRoute
  ExampleIndexRoute: typeof ExampleIndexRoute
  OrganizationIndexRoute: typeof OrganizationIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$': {
      id: '/$'
      path: '/$'
      fullPath: '/$'
      preLoaderRoute: typeof SplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/organization/': {
      id: '/organization/'
      path: '/organization'
      fullPath: '/organization'
      preLoaderRoute: typeof OrganizationIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/example/': {
      id: '/example/'
      path: '/example'
      fullPath: '/example'
      preLoaderRoute: typeof ExampleIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account/': {
      id: '/account/'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AccountIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/organization/$organizationView': {
      id: '/organization/$organizationView'
      path: '/organization/$organizationView'
      fullPath: '/organization/$organizationView'
      preLoaderRoute: typeof OrganizationOrganizationViewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/example/$featureId': {
      id: '/example/$featureId'
      path: '/example/$featureId'
      fullPath: '/example/$featureId'
      preLoaderRoute: typeof ExampleFeatureIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/$authView': {
      id: '/auth/$authView'
      path: '/auth/$authView'
      fullPath: '/auth/$authView'
      preLoaderRoute: typeof AuthAuthViewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/$': {
      id: '/api/$'
      path: '/api/$'
      fullPath: '/api/$'
      preLoaderRoute: typeof ApiSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/quiz-editor': {
      id: '/admin/quiz-editor'
      path: '/quiz-editor'
      fullPath: '/admin/quiz-editor'
      preLoaderRoute: typeof AdminQuizEditorRouteImport
      parentRoute: typeof AdminRoute
    }
    '/account/$accountView': {
      id: '/account/$accountView'
      path: '/account/$accountView'
      fullPath: '/account/$accountView'
      preLoaderRoute: typeof AccountAccountViewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/responses/$responseId_new': {
      id: '/admin/responses/$responseId_new'
      path: '/responses/$responseId_new'
      fullPath: '/admin/responses/$responseId_new'
      preLoaderRoute: typeof AdminResponsesResponseId_newRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/responses/$responseId': {
      id: '/admin/responses/$responseId'
      path: '/responses/$responseId'
      fullPath: '/admin/responses/$responseId'
      preLoaderRoute: typeof AdminResponsesResponseIdRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/responses/$responseId/analysis': {
      id: '/admin/responses/$responseId/analysis'
      path: '/analysis'
      fullPath: '/admin/responses/$responseId/analysis'
      preLoaderRoute: typeof AdminResponsesResponseIdAnalysisRouteImport
      parentRoute: typeof AdminResponsesResponseIdRoute
    }
  }
}

interface AdminResponsesResponseIdRouteChildren {
  AdminResponsesResponseIdAnalysisRoute: typeof AdminResponsesResponseIdAnalysisRoute
}

const AdminResponsesResponseIdRouteChildren: AdminResponsesResponseIdRouteChildren =
  {
    AdminResponsesResponseIdAnalysisRoute:
      AdminResponsesResponseIdAnalysisRoute,
  }

const AdminResponsesResponseIdRouteWithChildren =
  AdminResponsesResponseIdRoute._addFileChildren(
    AdminResponsesResponseIdRouteChildren,
  )

interface AdminRouteChildren {
  AdminQuizEditorRoute: typeof AdminQuizEditorRoute
  AdminResponsesResponseIdRoute: typeof AdminResponsesResponseIdRouteWithChildren
  AdminResponsesResponseId_newRoute: typeof AdminResponsesResponseId_newRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminQuizEditorRoute: AdminQuizEditorRoute,
  AdminResponsesResponseIdRoute: AdminResponsesResponseIdRouteWithChildren,
  AdminResponsesResponseId_newRoute: AdminResponsesResponseId_newRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SplatRoute: SplatRoute,
  AdminRoute: AdminRouteWithChildren,
  AccountAccountViewRoute: AccountAccountViewRoute,
  ApiSplatRoute: ApiSplatRoute,
  AuthAuthViewRoute: AuthAuthViewRoute,
  ExampleFeatureIdRoute: ExampleFeatureIdRoute,
  OrganizationOrganizationViewRoute: OrganizationOrganizationViewRoute,
  AccountIndexRoute: AccountIndexRoute,
  ExampleIndexRoute: ExampleIndexRoute,
  OrganizationIndexRoute: OrganizationIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
