/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TodosRouteImport } from './routes/todos'
import { Route as ResultsRouteImport } from './routes/results'
import { Route as ResponsesRouteImport } from './routes/responses'
import { Route as QuizTakerRouteImport } from './routes/quiz-taker'
import { Route as QuizRouteImport } from './routes/quiz'
import { Route as ArtistTypesRouteImport } from './routes/artist-types'
import { Route as AnalysisRouteImport } from './routes/analysis'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as SplatRouteImport } from './routes/$'
import { Route as IndexRouteImport } from './routes/index'
import { Route as OrganizationIndexRouteImport } from './routes/organization/index'
import { Route as ExampleIndexRouteImport } from './routes/example/index'
import { Route as AccountIndexRouteImport } from './routes/account/index'
import { Route as TestAdminRouteImport } from './routes/test/admin'
import { Route as OrganizationOrganizationViewRouteImport } from './routes/organization/$organizationView'
import { Route as MyResponseResponseIdRouteImport } from './routes/my-response.$responseId'
import { Route as ExampleFeatureIdRouteImport } from './routes/example/$featureId'
import { Route as AuthAuthViewRouteImport } from './routes/auth/$authView'
import { Route as ApiSplatRouteImport } from './routes/api/$'
import { Route as AdminQuizEditorRouteImport } from './routes/admin/quiz-editor'
import { Route as AccountAccountViewRouteImport } from './routes/account/$accountView'
import { Route as AdminResponsesResponseId_newRouteImport } from './routes/admin/responses/$responseId_new'
import { Route as AdminResponsesResponseIdRouteImport } from './routes/admin/responses/$responseId'
import { Route as AdminResponsesResponseIdAnalysisRouteImport } from './routes/admin/responses/$responseId/analysis'

const TodosRoute = TodosRouteImport.update({
  id: '/todos',
  path: '/todos',
  getParentRoute: () => rootRouteImport,
} as any)
const ResultsRoute = ResultsRouteImport.update({
  id: '/results',
  path: '/results',
  getParentRoute: () => rootRouteImport,
} as any)
const ResponsesRoute = ResponsesRouteImport.update({
  id: '/responses',
  path: '/responses',
  getParentRoute: () => rootRouteImport,
} as any)
const QuizTakerRoute = QuizTakerRouteImport.update({
  id: '/quiz-taker',
  path: '/quiz-taker',
  getParentRoute: () => rootRouteImport,
} as any)
const QuizRoute = QuizRouteImport.update({
  id: '/quiz',
  path: '/quiz',
  getParentRoute: () => rootRouteImport,
} as any)
const ArtistTypesRoute = ArtistTypesRouteImport.update({
  id: '/artist-types',
  path: '/artist-types',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalysisRoute = AnalysisRouteImport.update({
  id: '/analysis',
  path: '/analysis',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const SplatRoute = SplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const OrganizationIndexRoute = OrganizationIndexRouteImport.update({
  id: '/organization/',
  path: '/organization/',
  getParentRoute: () => rootRouteImport,
} as any)
const ExampleIndexRoute = ExampleIndexRouteImport.update({
  id: '/example/',
  path: '/example/',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountIndexRoute = AccountIndexRouteImport.update({
  id: '/account/',
  path: '/account/',
  getParentRoute: () => rootRouteImport,
} as any)
const TestAdminRoute = TestAdminRouteImport.update({
  id: '/test/admin',
  path: '/test/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const OrganizationOrganizationViewRoute =
  OrganizationOrganizationViewRouteImport.update({
    id: '/organization/$organizationView',
    path: '/organization/$organizationView',
    getParentRoute: () => rootRouteImport,
  } as any)
const MyResponseResponseIdRoute = MyResponseResponseIdRouteImport.update({
  id: '/my-response/$responseId',
  path: '/my-response/$responseId',
  getParentRoute: () => rootRouteImport,
} as any)
const ExampleFeatureIdRoute = ExampleFeatureIdRouteImport.update({
  id: '/example/$featureId',
  path: '/example/$featureId',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthAuthViewRoute = AuthAuthViewRouteImport.update({
  id: '/auth/$authView',
  path: '/auth/$authView',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSplatRoute = ApiSplatRouteImport.update({
  id: '/api/$',
  path: '/api/$',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminQuizEditorRoute = AdminQuizEditorRouteImport.update({
  id: '/quiz-editor',
  path: '/quiz-editor',
  getParentRoute: () => AdminRoute,
} as any)
const AccountAccountViewRoute = AccountAccountViewRouteImport.update({
  id: '/account/$accountView',
  path: '/account/$accountView',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminResponsesResponseId_newRoute =
  AdminResponsesResponseId_newRouteImport.update({
    id: '/responses/$responseId_new',
    path: '/responses/$responseId_new',
    getParentRoute: () => AdminRoute,
  } as any)
const AdminResponsesResponseIdRoute =
  AdminResponsesResponseIdRouteImport.update({
    id: '/responses/$responseId',
    path: '/responses/$responseId',
    getParentRoute: () => AdminRoute,
  } as any)
const AdminResponsesResponseIdAnalysisRoute =
  AdminResponsesResponseIdAnalysisRouteImport.update({
    id: '/analysis',
    path: '/analysis',
    getParentRoute: () => AdminResponsesResponseIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/admin': typeof AdminRouteWithChildren
  '/analysis': typeof AnalysisRoute
  '/artist-types': typeof ArtistTypesRoute
  '/quiz': typeof QuizRoute
  '/quiz-taker': typeof QuizTakerRoute
  '/responses': typeof ResponsesRoute
  '/results': typeof ResultsRoute
  '/todos': typeof TodosRoute
  '/account/$accountView': typeof AccountAccountViewRoute
  '/admin/quiz-editor': typeof AdminQuizEditorRoute
  '/api/$': typeof ApiSplatRoute
  '/auth/$authView': typeof AuthAuthViewRoute
  '/example/$featureId': typeof ExampleFeatureIdRoute
  '/my-response/$responseId': typeof MyResponseResponseIdRoute
  '/organization/$organizationView': typeof OrganizationOrganizationViewRoute
  '/test/admin': typeof TestAdminRoute
  '/account': typeof AccountIndexRoute
  '/example': typeof ExampleIndexRoute
  '/organization': typeof OrganizationIndexRoute
  '/admin/responses/$responseId': typeof AdminResponsesResponseIdRouteWithChildren
  '/admin/responses/$responseId_new': typeof AdminResponsesResponseId_newRoute
  '/admin/responses/$responseId/analysis': typeof AdminResponsesResponseIdAnalysisRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/admin': typeof AdminRouteWithChildren
  '/analysis': typeof AnalysisRoute
  '/artist-types': typeof ArtistTypesRoute
  '/quiz': typeof QuizRoute
  '/quiz-taker': typeof QuizTakerRoute
  '/responses': typeof ResponsesRoute
  '/results': typeof ResultsRoute
  '/todos': typeof TodosRoute
  '/account/$accountView': typeof AccountAccountViewRoute
  '/admin/quiz-editor': typeof AdminQuizEditorRoute
  '/api/$': typeof ApiSplatRoute
  '/auth/$authView': typeof AuthAuthViewRoute
  '/example/$featureId': typeof ExampleFeatureIdRoute
  '/my-response/$responseId': typeof MyResponseResponseIdRoute
  '/organization/$organizationView': typeof OrganizationOrganizationViewRoute
  '/test/admin': typeof TestAdminRoute
  '/account': typeof AccountIndexRoute
  '/example': typeof ExampleIndexRoute
  '/organization': typeof OrganizationIndexRoute
  '/admin/responses/$responseId': typeof AdminResponsesResponseIdRouteWithChildren
  '/admin/responses/$responseId_new': typeof AdminResponsesResponseId_newRoute
  '/admin/responses/$responseId/analysis': typeof AdminResponsesResponseIdAnalysisRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/admin': typeof AdminRouteWithChildren
  '/analysis': typeof AnalysisRoute
  '/artist-types': typeof ArtistTypesRoute
  '/quiz': typeof QuizRoute
  '/quiz-taker': typeof QuizTakerRoute
  '/responses': typeof ResponsesRoute
  '/results': typeof ResultsRoute
  '/todos': typeof TodosRoute
  '/account/$accountView': typeof AccountAccountViewRoute
  '/admin/quiz-editor': typeof AdminQuizEditorRoute
  '/api/$': typeof ApiSplatRoute
  '/auth/$authView': typeof AuthAuthViewRoute
  '/example/$featureId': typeof ExampleFeatureIdRoute
  '/my-response/$responseId': typeof MyResponseResponseIdRoute
  '/organization/$organizationView': typeof OrganizationOrganizationViewRoute
  '/test/admin': typeof TestAdminRoute
  '/account/': typeof AccountIndexRoute
  '/example/': typeof ExampleIndexRoute
  '/organization/': typeof OrganizationIndexRoute
  '/admin/responses/$responseId': typeof AdminResponsesResponseIdRouteWithChildren
  '/admin/responses/$responseId_new': typeof AdminResponsesResponseId_newRoute
  '/admin/responses/$responseId/analysis': typeof AdminResponsesResponseIdAnalysisRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$'
    | '/admin'
    | '/analysis'
    | '/artist-types'
    | '/quiz'
    | '/quiz-taker'
    | '/responses'
    | '/results'
    | '/todos'
    | '/account/$accountView'
    | '/admin/quiz-editor'
    | '/api/$'
    | '/auth/$authView'
    | '/example/$featureId'
    | '/my-response/$responseId'
    | '/organization/$organizationView'
    | '/test/admin'
    | '/account'
    | '/example'
    | '/organization'
    | '/admin/responses/$responseId'
    | '/admin/responses/$responseId_new'
    | '/admin/responses/$responseId/analysis'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$'
    | '/admin'
    | '/analysis'
    | '/artist-types'
    | '/quiz'
    | '/quiz-taker'
    | '/responses'
    | '/results'
    | '/todos'
    | '/account/$accountView'
    | '/admin/quiz-editor'
    | '/api/$'
    | '/auth/$authView'
    | '/example/$featureId'
    | '/my-response/$responseId'
    | '/organization/$organizationView'
    | '/test/admin'
    | '/account'
    | '/example'
    | '/organization'
    | '/admin/responses/$responseId'
    | '/admin/responses/$responseId_new'
    | '/admin/responses/$responseId/analysis'
  id:
    | '__root__'
    | '/'
    | '/$'
    | '/admin'
    | '/analysis'
    | '/artist-types'
    | '/quiz'
    | '/quiz-taker'
    | '/responses'
    | '/results'
    | '/todos'
    | '/account/$accountView'
    | '/admin/quiz-editor'
    | '/api/$'
    | '/auth/$authView'
    | '/example/$featureId'
    | '/my-response/$responseId'
    | '/organization/$organizationView'
    | '/test/admin'
    | '/account/'
    | '/example/'
    | '/organization/'
    | '/admin/responses/$responseId'
    | '/admin/responses/$responseId_new'
    | '/admin/responses/$responseId/analysis'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SplatRoute: typeof SplatRoute
  AdminRoute: typeof AdminRouteWithChildren
  AnalysisRoute: typeof AnalysisRoute
  ArtistTypesRoute: typeof ArtistTypesRoute
  QuizRoute: typeof QuizRoute
  QuizTakerRoute: typeof QuizTakerRoute
  ResponsesRoute: typeof ResponsesRoute
  ResultsRoute: typeof ResultsRoute
  TodosRoute: typeof TodosRoute
  AccountAccountViewRoute: typeof AccountAccountViewRoute
  ApiSplatRoute: typeof ApiSplatRoute
  AuthAuthViewRoute: typeof AuthAuthViewRoute
  ExampleFeatureIdRoute: typeof ExampleFeatureIdRoute
  MyResponseResponseIdRoute: typeof MyResponseResponseIdRoute
  OrganizationOrganizationViewRoute: typeof OrganizationOrganizationViewRoute
  TestAdminRoute: typeof TestAdminRoute
  AccountIndexRoute: typeof AccountIndexRoute
  ExampleIndexRoute: typeof ExampleIndexRoute
  OrganizationIndexRoute: typeof OrganizationIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/todos': {
      id: '/todos'
      path: '/todos'
      fullPath: '/todos'
      preLoaderRoute: typeof TodosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/results': {
      id: '/results'
      path: '/results'
      fullPath: '/results'
      preLoaderRoute: typeof ResultsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/responses': {
      id: '/responses'
      path: '/responses'
      fullPath: '/responses'
      preLoaderRoute: typeof ResponsesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quiz-taker': {
      id: '/quiz-taker'
      path: '/quiz-taker'
      fullPath: '/quiz-taker'
      preLoaderRoute: typeof QuizTakerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quiz': {
      id: '/quiz'
      path: '/quiz'
      fullPath: '/quiz'
      preLoaderRoute: typeof QuizRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/artist-types': {
      id: '/artist-types'
      path: '/artist-types'
      fullPath: '/artist-types'
      preLoaderRoute: typeof ArtistTypesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analysis': {
      id: '/analysis'
      path: '/analysis'
      fullPath: '/analysis'
      preLoaderRoute: typeof AnalysisRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$': {
      id: '/$'
      path: '/$'
      fullPath: '/$'
      preLoaderRoute: typeof SplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/organization/': {
      id: '/organization/'
      path: '/organization'
      fullPath: '/organization'
      preLoaderRoute: typeof OrganizationIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/example/': {
      id: '/example/'
      path: '/example'
      fullPath: '/example'
      preLoaderRoute: typeof ExampleIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account/': {
      id: '/account/'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AccountIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/test/admin': {
      id: '/test/admin'
      path: '/test/admin'
      fullPath: '/test/admin'
      preLoaderRoute: typeof TestAdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/organization/$organizationView': {
      id: '/organization/$organizationView'
      path: '/organization/$organizationView'
      fullPath: '/organization/$organizationView'
      preLoaderRoute: typeof OrganizationOrganizationViewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/my-response/$responseId': {
      id: '/my-response/$responseId'
      path: '/my-response/$responseId'
      fullPath: '/my-response/$responseId'
      preLoaderRoute: typeof MyResponseResponseIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/example/$featureId': {
      id: '/example/$featureId'
      path: '/example/$featureId'
      fullPath: '/example/$featureId'
      preLoaderRoute: typeof ExampleFeatureIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/$authView': {
      id: '/auth/$authView'
      path: '/auth/$authView'
      fullPath: '/auth/$authView'
      preLoaderRoute: typeof AuthAuthViewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/$': {
      id: '/api/$'
      path: '/api/$'
      fullPath: '/api/$'
      preLoaderRoute: typeof ApiSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/quiz-editor': {
      id: '/admin/quiz-editor'
      path: '/quiz-editor'
      fullPath: '/admin/quiz-editor'
      preLoaderRoute: typeof AdminQuizEditorRouteImport
      parentRoute: typeof AdminRoute
    }
    '/account/$accountView': {
      id: '/account/$accountView'
      path: '/account/$accountView'
      fullPath: '/account/$accountView'
      preLoaderRoute: typeof AccountAccountViewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/responses/$responseId_new': {
      id: '/admin/responses/$responseId_new'
      path: '/responses/$responseId_new'
      fullPath: '/admin/responses/$responseId_new'
      preLoaderRoute: typeof AdminResponsesResponseId_newRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/responses/$responseId': {
      id: '/admin/responses/$responseId'
      path: '/responses/$responseId'
      fullPath: '/admin/responses/$responseId'
      preLoaderRoute: typeof AdminResponsesResponseIdRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/responses/$responseId/analysis': {
      id: '/admin/responses/$responseId/analysis'
      path: '/analysis'
      fullPath: '/admin/responses/$responseId/analysis'
      preLoaderRoute: typeof AdminResponsesResponseIdAnalysisRouteImport
      parentRoute: typeof AdminResponsesResponseIdRoute
    }
  }
}

interface AdminResponsesResponseIdRouteChildren {
  AdminResponsesResponseIdAnalysisRoute: typeof AdminResponsesResponseIdAnalysisRoute
}

const AdminResponsesResponseIdRouteChildren: AdminResponsesResponseIdRouteChildren =
  {
    AdminResponsesResponseIdAnalysisRoute:
      AdminResponsesResponseIdAnalysisRoute,
  }

const AdminResponsesResponseIdRouteWithChildren =
  AdminResponsesResponseIdRoute._addFileChildren(
    AdminResponsesResponseIdRouteChildren,
  )

interface AdminRouteChildren {
  AdminQuizEditorRoute: typeof AdminQuizEditorRoute
  AdminResponsesResponseIdRoute: typeof AdminResponsesResponseIdRouteWithChildren
  AdminResponsesResponseId_newRoute: typeof AdminResponsesResponseId_newRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminQuizEditorRoute: AdminQuizEditorRoute,
  AdminResponsesResponseIdRoute: AdminResponsesResponseIdRouteWithChildren,
  AdminResponsesResponseId_newRoute: AdminResponsesResponseId_newRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SplatRoute: SplatRoute,
  AdminRoute: AdminRouteWithChildren,
  AnalysisRoute: AnalysisRoute,
  ArtistTypesRoute: ArtistTypesRoute,
  QuizRoute: QuizRoute,
  QuizTakerRoute: QuizTakerRoute,
  ResponsesRoute: ResponsesRoute,
  ResultsRoute: ResultsRoute,
  TodosRoute: TodosRoute,
  AccountAccountViewRoute: AccountAccountViewRoute,
  ApiSplatRoute: ApiSplatRoute,
  AuthAuthViewRoute: AuthAuthViewRoute,
  ExampleFeatureIdRoute: ExampleFeatureIdRoute,
  MyResponseResponseIdRoute: MyResponseResponseIdRoute,
  OrganizationOrganizationViewRoute: OrganizationOrganizationViewRoute,
  TestAdminRoute: TestAdminRoute,
  AccountIndexRoute: AccountIndexRoute,
  ExampleIndexRoute: ExampleIndexRoute,
  OrganizationIndexRoute: OrganizationIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
