/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ChatRouteImport } from './routes/chat'
import { Route as AnnouncementsRouteImport } from './routes/announcements'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiEventsRouteImport } from './routes/api/events'
import { Route as ApiChatRouteImport } from './routes/api/chat'
import { Route as ApiAnnouncementsRouteImport } from './routes/api/announcements'

const ChatRoute = ChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const AnnouncementsRoute = AnnouncementsRouteImport.update({
  id: '/announcements',
  path: '/announcements',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiEventsRoute = ApiEventsRouteImport.update({
  id: '/api/events',
  path: '/api/events',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiChatRoute = ApiChatRouteImport.update({
  id: '/api/chat',
  path: '/api/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAnnouncementsRoute = ApiAnnouncementsRouteImport.update({
  id: '/api/announcements',
  path: '/api/announcements',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/announcements': typeof AnnouncementsRoute
  '/chat': typeof ChatRoute
  '/api/announcements': typeof ApiAnnouncementsRoute
  '/api/chat': typeof ApiChatRoute
  '/api/events': typeof ApiEventsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/announcements': typeof AnnouncementsRoute
  '/chat': typeof ChatRoute
  '/api/announcements': typeof ApiAnnouncementsRoute
  '/api/chat': typeof ApiChatRoute
  '/api/events': typeof ApiEventsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/announcements': typeof AnnouncementsRoute
  '/chat': typeof ChatRoute
  '/api/announcements': typeof ApiAnnouncementsRoute
  '/api/chat': typeof ApiChatRoute
  '/api/events': typeof ApiEventsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/announcements'
    | '/chat'
    | '/api/announcements'
    | '/api/chat'
    | '/api/events'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/announcements'
    | '/chat'
    | '/api/announcements'
    | '/api/chat'
    | '/api/events'
  id:
    | '__root__'
    | '/'
    | '/announcements'
    | '/chat'
    | '/api/announcements'
    | '/api/chat'
    | '/api/events'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AnnouncementsRoute: typeof AnnouncementsRoute
  ChatRoute: typeof ChatRoute
  ApiAnnouncementsRoute: typeof ApiAnnouncementsRoute
  ApiChatRoute: typeof ApiChatRoute
  ApiEventsRoute: typeof ApiEventsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/chat': {
      id: '/chat'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof ChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/announcements': {
      id: '/announcements'
      path: '/announcements'
      fullPath: '/announcements'
      preLoaderRoute: typeof AnnouncementsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/events': {
      id: '/api/events'
      path: '/api/events'
      fullPath: '/api/events'
      preLoaderRoute: typeof ApiEventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/chat': {
      id: '/api/chat'
      path: '/api/chat'
      fullPath: '/api/chat'
      preLoaderRoute: typeof ApiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/announcements': {
      id: '/api/announcements'
      path: '/api/announcements'
      fullPath: '/api/announcements'
      preLoaderRoute: typeof ApiAnnouncementsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AnnouncementsRoute: AnnouncementsRoute,
  ChatRoute: ChatRoute,
  ApiAnnouncementsRoute: ApiAnnouncementsRoute,
  ApiChatRoute: ApiChatRoute,
  ApiEventsRoute: ApiEventsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
